# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: authorizer
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 10
    volumeType: gp2
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        ebs: true
iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    attachPolicyARNs:
    - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

cloudWatch:
  clusterLogging:
      # enable specific types of cluster control plane logs
      enableTypes: ["audit", "authenticator", "controllerManager"]
      # all supported types: "api", "audit", "authenti